<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MedicalTest extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', // Nombre del examen médico
        'description', // Descripción del examen médico
        'price', // Precio del examen médico
    ];

    /**
     * Get the orders associated with the medical test.
     */
    public function orders()
    {
        return $this->belongsToMany(Order::class, 'order_details', 'fk_medical_test', 'fk_order');
    }

    /**
     * Calculate the total revenue generated by this medical test.
     *
     * @return float
     */
    public function calculateTotalRevenue()
    {
        // Puedes agregar lógica aquí para calcular el total de ingresos generados por este examen médico
        // Esto podría ser la suma de todos los precios de los exámenes asociados
        return $this->orders()->sum('price');
    }

    /**
     * Format the price as currency.
     *
     * @return string
     */
    public function formattedPrice()
    {
        // Puedes agregar lógica aquí para formatear el precio como moneda
        return '$' . number_format($this->price, 2);
    }
}
